from decouple import config


SECRET_KEY = config('SECRET_KEY')
HASH_ALGORITHM = config('HASH_ALGORITHM')
ACCESS_TOKEN_EXPIRE_SECONDS = int(config('ACCESS_TOKEN_EXPIRE_SECONDS'))
REFRESH_TOKEN_EXPIRE_SECONDS = int(config('REFRESH_TOKEN_EXPIRE_SECONDS'))

OPENAI_API_KEY = config('OPENAI_API_KEY')
ASSISTANT_MODEL = config('ASSISTANT_MODEL')
ASSISTANT_ID = config('ASSISTANT_ID')

GOOGLE_SHEET_ID = config('GOOGLE_SHEET_ID')
DATABASE_URL = config('DATABASE_URL')
